site_name: Katechizm Gasparriego
site_description: Katechizm katolicki kard. Gasparriego
site_author: Paweł Grabowski
site_dir: dist
docs_dir: src

theme:
  name: material

extra_javascript:
  - js/utils.js

plugins:
  - search
  - awesome-pages
  - minify:
      minify_html: true

markdown_extensions:
  - meta
  - pymdownx.mark
